title: "India's Blog" # the name of your site, e.g. ACME Corp.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
paginate: null # the number of posts to show on each page of the site
future: true